# Generated by Django 4.1.2 on 2023-03-09 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modeles',
            fields=[
                ('pathmodele', models.TextField(blank=True, null=True)),
                ('namemodel', models.TextField(blank=True)),
                ('listctg', models.TextField(blank=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('perf', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
            options={
                'db_table': 'Modeles',
            },
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('pathimg', models.TextField()),
                ('date', models.TextField(blank=True, null=True)),
                ('heure', models.TextField(blank=True, null=True)),
                ('ctgbyuser', models.TextField()),
                ('ctgbymodel', models.TextField()),
                ('namemodel', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Monitoring',
            },
        ),
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('pathimg', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'MultipleImage',
            },
        ),
    ]
