# Generated by Django 4.1.6 on 2023-03-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modeles',
            fields=[
                ('pathmodele', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Modeles',
            },
        ),
        migrations.AddField(
            model_name='monitoring',
            name='heure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
