# Generated by Django 4.1.6 on 2023-03-09 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_modeles_monitoring_heure_alter_monitoring_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeles',
            name='listctg',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modeles',
            name='namemodel',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modeles',
            name='perf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
